[env:esp32cam-car]
platform = espressif32
board = esp32cam
board_build.psram = enabled
framework = arduino
board_build.partitions = partitions-4M.csv
monitor_speed = 115200

upload_protocol = espota
upload_port = esp32cam-a882c34c.local
upload_flags =
  --auth=mysecurepassword